### ISSUE TITLE
RAFT Model

### ISSUE THREAD

**Issue by TonyLianLong** [karazijal/guess-what-moves#2]
Thanks for your great work! It says in paper that an off-the-shelf RAFT model is used. However, there are several RAFT checkpoints being offered on the Github repo (https://github.com/princeton-vl/RAFT).

Would you mind indicating which one (e.g. raft-chairs.pth, raft-things.pth, raft-sintel.pth) is the RAFT checkpoint you use to generate the RAFT flow in your paper?

**Comment by karazijal** [comment]
Hi, 

We used the RAFT model implementation available [here](https://github.com/princeton-vl/RAFT), with `raft-things.pth` available [here](https://drive.google.com/drive/folders/1sWDsfuZ3Up38EUQt7-JDTT1HcGHuJgvT). That is, _not the torchvision version_. Hope this helps.

Best,
